apiVersion: apps/v1
kind: Deployment
metadata:
  name: hyperflow-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      component: hyperflow-engine
      name: hyperflow-engine
  template:
    metadata:
      labels:
        component: hyperflow-engine
        name: hyperflow-engine
    spec:
      containers:
      - command:
        - /bin/sh
        - -c
        - "echo \"Hyperflow environmental variables:\" ; env | grep \"HF_\" ; while\
          \ ! [ -f /work_dir/workflow.json ]; do echo \"Waiting for workflow.json\
          \ to be mounted...\" ; done ; echo \"Workflow data mounted: \" ; ls -la\
          \ /work_dir ; if [ $HF_VAR_DEBUG -eq 0 ] ; then\n  cd /work_dir/ ;\n  echo\
          \ \"Running workflow:\" ;\n  hflow run workflow.json ;\n  if [ -d /work_dir/logs-hf\
          \ ] ; then\n    hflow-info /work_dir/workflow.json --print -f /work_dir\
          \ > /work_dir/logs-hf/file_sizes.log 2>&1 ;\n    cat /work_dir/logs-hf/file_sizes.log\
          \ ;\n    echo 1 > /work_dir/postprocStart ;\n  else\n    echo \"Hyperflow\
          \ logs not collected. Something must have gone wrong!\"\n  fi ;\n  echo\
          \ \"Workflow finished. Container is waiting for manual termination.\" ;\n\
          \  while true; do sleep 5 ; done ;\nelse\n  while true; do sleep 5 ; done\
          \ ;\nfi ;\n"
        env:
        - name: REDIS_URL
          value: redis://redis.default.svc.cluster.local:6379
        - name: HF_VAR_function
          value: k8sCommand
        - name: HF_VAR_JOB_TEMPLATE_PATH
          value: /opt/hyperflow/job-template.yaml
        - name: HF_VAR_WORKER_CONTAINER
          value: hyperflowwms/soykb-workflow-worker:v1.0.11
        - name: HF_VAR_WORK_DIR
          value: /work_dir
        - name: HF_VAR_DEBUG
          value: '0'
        - name: HF_VAR_BACKOFF_LIMIT
          value: '0'
        - name: HF_VAR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        image: matplinta/hyperflow:1.0
        imagePullPolicy: Always
        name: hyperflow
        volumeMounts:
        - mountPath: /work_dir:shared
          name: workflow-data
        - mountPath: /opt/hyperflow/job-template.yaml
          name: config-map
          readOnly: true
          subPath: job-template.yaml
      volumes:
      - configMap:
          name: hyperflow-config
        name: config-map
      - name: workflow-data
        persistentVolumeClaim:
          claimName: nfs
