apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-server
spec:
  replicas: 1
  selector:
    matchLabels:
      role: nfs-server
  template:
    metadata:
      labels:
        role: nfs-server
    spec:
      containers:
      - command:
        - /bin/bash
        - -c
        - 'while [ ! -d /workflow-data ] ; do "Waiting for /workflow-data to created"
          ; sleep 1 ; done ;  while [ -z "$(ls -A /workflow-data)" ]; do echo "Waiting
          for /workflow-data to be mounted" ; sleep 1 ; done ; echo "Copying content
          /workflow-data to /exports" ; cp -vr  /workflow-data/* /exports/ ; /usr/local/bin/run_nfs.sh
          /exports / ;

          '
        image: gcr.io/google_containers/volume-nfs:0.8
        name: nfs-server
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 20048
          name: mountd
        - containerPort: 111
          name: rpcbind
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /workflow-data:shared
          name: workflow-data
      - command:
        - /bin/sh
        - -c
        - 'mount -o bind /data /workflow-data ; sleep 3600000 ;

          '
        image: hyperflowwms/soykb-workflow-data:hyperflow-soykb-example-f6f69d6ca3ebd9fe2458804b59b4ef71
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - sh
              - -c
              - 'umount -fl /workflow-data;

                '
        name: workflow-data
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
          privileged: true
        volumeMounts:
        - mountPath: /workflow-data:shared
          name: workflow-data
      volumes:
      - emptyDir: {}
        name: workflow-data
