apiVersion: batch/v1
kind: Job
metadata:
  name: logs-parser
spec:
  template:
    metadata:
      labels:
        name: logs-parser
        component: logs-parser
    spec:
      restartPolicy: Never
      containers:
      - name: parser
        image: matplinta/logs-parser:1.0
        imagePullPolicy: Always
        command:
          - "/bin/sh"
          - "-c"
          - >
            while ! [ -f /work_dir/postprocStart ]; do echo "Waiting for postprocStart flag to be mounted..." ; done ;
            echo "postprocStart flag mounted: " ; ls -la /work_dir ;
            python3 /parser.py -s /work_dir/logs-hf -d /work_dir
        volumeMounts:
           - name: workflow-data
             mountPath: "/work_dir:shared"
      volumes:
      - name: workflow-data
        persistentVolumeClaim:
          claimName: nfs

